#! /usr/bin/env python
# encoding: utf-8

subdirs = [
    'hardbody',
    '2010.arjunan.syst.synth.biol'
    ]

def configure(conf):
    conf.recurse(subdirs)

def build(bld):
    bld.recurse(subdirs)
