#! /usr/bin/env python
# encoding: utf-8

from waflib.Tools import waf_unit_test
from waflib import Logs

top = '.'
out = 'build'

pyfiles = [
    '__init__.py',
    'particle_space.py',
    'spatiocyte_tools.py',
    'bdml.py',
    'particle_spatiocyte_loader.py',
    'lattice_space.py',
    'sbml_exporter.py'
    ]


def options(opt):
    opt.load('compiler_cxx') # XXX: DUMMY
    opt.load('python')

def configure(conf):
    conf.load('compiler_cxx') # XXX: DUMMY
    conf.load('python')
    conf.check_python_headers()

def build(bld):
    bld.install_files('${PYTHONDIR}/ecell4/export', pyfiles)
