#!/usr/bin/env python
# encoding: utf-8

from waflib.Tools import waf_unit_test
from waflib import Logs


def configure(conf):
    pass

def build(bld):
    bld.program(
        features='cxx cxxprogram test',
        source='GillespieWorld_test.cpp',
        target='GillespieWorld_test',
        includes=['..'],
        lib=['ecell4-core', 'gsl', 'gslcblas', 'm'],
        use='ecell4-gillespie')

    bld.program(
        features='cxx cxxprogram test',
        source='GillespieSimulator_test.cpp',
        target='GillespieSimulator_test',
        includes=['..'],
        lib=['ecell4-core', 'gsl', 'gslcblas', 'm'],
        use='ecell4-gillespie')
