#! /usr/bin/env python
# encoding: utf-8

def configure(conf):
    pass

def build(bld):
    bld.program(
        features='cxx cxxprogram test',
        source='Position3_test.cpp',
        target='Position3_test',
        includes='..',
        lib=['gsl', 'gslcblas', 'm'],
        use='unittestmain ecell4-core CPPUNIT')

    bld.program(
        features='cxx cxxprogram test',
        source='GSLRandomNumberGenerator_test.cpp',
        target='GSLRandomNumberGenerator_test',
        includes='..',
        lib=['gsl', 'gslcblas', 'm'],
        use='unittestmain ecell4-core CPPUNIT')

    bld.program(
        features='cxx cxxprogram test',
        source='CompartmentSpaceVectorImpl_test.cpp',
        target='CompartmentSpaceVectorImpl_test',
        includes='..',
        lib=['gsl', 'gslcblas', 'm'],
        use='unittestmain ecell4-core CPPUNIT')

    bld.program(
        features='cxx cxxstlib',
        source='main.cpp',
        use='CPPUNIT',
        target='unittestmain')
