#! /usr/bin/env python
# encoding: utf-8


def configure(conf):
    pass

def build(bld):
    bld.program(
        source = 'main.cpp',
        target = 'hardbody',
        includes = ['../..'],
        lib = ['gsl', 'gslcblas', 'm', 'ecell4-core', 'hdf5', 'hdf5_cpp'],
        use = 'ecell4-bd')
