



DATADIR=/home/shafi/run/mapk/09-4/data/
#DATADIR=./data
# PATTERNS=\
# mapk3_1e-15_0.03125_fixed_1e-6_normal_ALL_reactions.dat\
# mapk3_1e-15_0.0625_fixed_1e-6_normal_ALL_reactions.dat\
# mapk3_1e-15_0.25_fixed_1e-6_normal_ALL_reactions.dat\
# mapk3_1e-15_1_fixed_1e-6_normal_ALL_reactions.dat\
# mapk3_1e-15_4_fixed_1e-6_normal_ALL_reactions.dat\
# mapk3_1e-15_0.03125_fixed_1e-2_normal_ALL_reactions.dat\
# mapk3_1e-15_0.0625_fixed_1e-2_normal_ALL_reactions.dat\
# mapk3_1e-15_0.25_fixed_1e-2_normal_ALL_reactions.dat\
# mapk3_1e-15_1_fixed_1e-2_normal_ALL_reactions.dat\
# mapk3_1e-15_4_fixed_1e-2_normal_ALL_reactions.dat\


DATADIR=./09-5/data
PATTERNS=\
mapk3-c_3.3e-15_1_fixed_0_normal_ALL_reactions.dat\
mapk3-c_3.3e-15_1_fixed_1e-1_normal_ALL_reactions.dat\
mapk3-c_3.3e-15_1_fixed_1e-2_normal_ALL_reactions.dat\
mapk3-c_3.3e-15_1_fixed_1e-3_normal_ALL_reactions.dat\
mapk3-c_3.3e-15_1_fixed_1e-4_normal_ALL_reactions.dat\
mapk3-c_3.3e-15_1_fixed_1e-5_normal_ALL_reactions.dat\
mapk3-c_3.3e-15_1_fixed_1e-6_normal_ALL_reactions.dat\
mapk3-c_1e-15_1_fixed_0_normal_ALL_reactions.dat\
mapk3-c_1e-15_1_fixed_1e-1_normal_ALL_reactions.dat\
mapk3-c_1e-15_1_fixed_1e-2_normal_ALL_reactions.dat\
mapk3-c_1e-15_1_fixed_1e-3_normal_ALL_reactions.dat\
mapk3-c_1e-15_1_fixed_1e-4_normal_ALL_reactions.dat\
mapk3-c_1e-15_1_fixed_1e-5_normal_ALL_reactions.dat\
mapk3-c_1e-15_1_fixed_1e-6_normal_ALL_reactions.dat\
mapk3-c_1e-16_1_fixed_0_normal_ALL_reactions.dat\
mapk3-c_1e-16_1_fixed_1e-1_normal_ALL_reactions.dat\
mapk3-c_1e-16_1_fixed_1e-2_normal_ALL_reactions.dat\
mapk3-c_1e-16_1_fixed_1e-3_normal_ALL_reactions.dat\
mapk3-c_1e-16_1_fixed_1e-4_normal_ALL_reactions.dat\
mapk3-c_1e-16_1_fixed_1e-5_normal_ALL_reactions.dat\
mapk3-c_1e-16_1_fixed_1e-6_normal_ALL_reactions.dat\
mapk3-c_1e-17_1_fixed_0_normal_ALL_reactions.dat\
mapk3-c_1e-17_1_fixed_1e-1_normal_ALL_reactions.dat\
mapk3-c_1e-17_1_fixed_1e-2_normal_ALL_reactions.dat\
mapk3-c_1e-17_1_fixed_1e-3_normal_ALL_reactions.dat\
mapk3-c_1e-17_1_fixed_1e-4_normal_ALL_reactions.dat\
mapk3-c_1e-17_1_fixed_1e-5_normal_ALL_reactions.dat\
mapk3-c_1e-17_1_fixed_1e-6_normal_ALL_reactions.dat\
mapk3-c_3.3e-16_1_fixed_0_normal_ALL_reactions.dat\
mapk3-c_3.3e-16_1_fixed_1e-1_normal_ALL_reactions.dat\
mapk3-c_3.3e-16_1_fixed_1e-2_normal_ALL_reactions.dat\
mapk3-c_3.3e-16_1_fixed_1e-3_normal_ALL_reactions.dat\
mapk3-c_3.3e-16_1_fixed_1e-4_normal_ALL_reactions.dat\
mapk3-c_3.3e-16_1_fixed_1e-5_normal_ALL_reactions.dat\
mapk3-c_3.3e-16_1_fixed_1e-6_normal_ALL_reactions.dat\
mapk3-c_3.3e-17_1_fixed_0_normal_ALL_reactions.dat\
mapk3-c_3.3e-17_1_fixed_1e-1_normal_ALL_reactions.dat\
mapk3-c_3.3e-17_1_fixed_1e-2_normal_ALL_reactions.dat\
mapk3-c_3.3e-17_1_fixed_1e-3_normal_ALL_reactions.dat\
mapk3-c_3.3e-17_1_fixed_1e-4_normal_ALL_reactions.dat\
mapk3-c_3.3e-17_1_fixed_1e-5_normal_ALL_reactions.dat\
mapk3-c_3.3e-17_1_fixed_1e-6_normal_ALL_reactions.dat\
\





# DATADIR=./09/data
# PATTERNS=\
# mapk3_1e-15_0.25_fixed_0_normal_ALL_reactions.dat\
# mapk3_1e-15_0.5_fixed_0_normal_ALL_reactions.dat\
# mapk3_1e-15_1_fixed_0_normal_ALL_reactions.dat\
# mapk3_1e-15_2_fixed_0_normal_ALL_reactions.dat\
# mapk3_1e-15_4_fixed_0_normal_ALL_reactions.dat\
# mapk3_1e-15_0.25_fixed_1e-6_normal_ALL_reactions.dat\
# mapk3_1e-15_0.5_fixed_1e-6_normal_ALL_reactions.dat\
# mapk3_1e-15_1_fixed_1e-6_normal_ALL_reactions.dat\
# mapk3_1e-15_2_fixed_1e-6_normal_ALL_reactions.dat\
# mapk3_1e-15_4_fixed_1e-6_normal_ALL_reactions.dat\
# mapk3_1e-15_0.25_fixed_1e-5_normal_ALL_reactions.dat\
# mapk3_1e-15_0.5_fixed_1e-5_normal_ALL_reactions.dat\
# mapk3_1e-15_1_fixed_1e-5_normal_ALL_reactions.dat\
# mapk3_1e-15_2_fixed_1e-5_normal_ALL_reactions.dat\
# mapk3_1e-15_4_fixed_1e-5_normal_ALL_reactions.dat\
# mapk3_1e-15_0.25_fixed_1e-4_normal_ALL_reactions.dat\
# mapk3_1e-15_0.5_fixed_1e-4_normal_ALL_reactions.dat\
# mapk3_1e-15_1_fixed_1e-4_normal_ALL_reactions.dat\
# mapk3_1e-15_2_fixed_1e-4_normal_ALL_reactions.dat\
# mapk3_1e-15_4_fixed_1e-4_normal_ALL_reactions.dat\
# mapk3_1e-15_0.25_fixed_1e-3_normal_ALL_reactions.dat\
# mapk3_1e-15_0.5_fixed_1e-3_normal_ALL_reactions.dat\
# mapk3_1e-15_1_fixed_1e-3_normal_ALL_reactions.dat\
# mapk3_1e-15_2_fixed_1e-3_normal_ALL_reactions.dat\
# mapk3_1e-15_4_fixed_1e-3_normal_ALL_reactions.dat\
# mapk3_1e-15_0.25_fixed_1e-2_normal_ALL_reactions.dat\
# mapk3_1e-15_0.5_fixed_1e-2_normal_ALL_reactions.dat\
# mapk3_1e-15_1_fixed_1e-2_normal_ALL_reactions.dat\
# mapk3_1e-15_2_fixed_1e-2_normal_ALL_reactions.dat\
# mapk3_1e-15_4_fixed_1e-2_normal_ALL_reactions.dat\
# mapk3_1e-15_0.25_fixed_1e-1_normal_ALL_reactions.dat\
# mapk3_1e-15_0.5_fixed_1e-1_normal_ALL_reactions.dat\
# mapk3_1e-15_1_fixed_1e-1_normal_ALL_reactions.dat\
# mapk3_1e-15_2_fixed_1e-1_normal_ALL_reactions.dat\
# mapk3_1e-15_4_fixed_1e-1_normal_ALL_reactions.dat\

REBIND=$(PATTERNS:.dat=.rebind)


# eratio:
# 	for i in $(PATTERNS); do ../../../bin/event_ratio.py $$i ; done


all-local: $(REBIND)

$(REBIND):
	python ../second_phos_ratio.py $(DATADIR)/$(@:.rebind=.dat);

#	python ../rebind_ratio.py $(DATADIR)/$(@:.rebind=.dat); \


plot:
	python plot.py



clean:
	rm -f *.rebind
