#! /usr/bin/env python
# encoding: utf-8

def configure(conf):
    pass

def build(bld):
    bld.program(
        features='cxx cxxprogram test',
        source=['EGFRDSimulatorWrapper_test.cpp'],
        target='EGFRDSimulatorWrapper_test',
        includes=['..', '../../../epdp'],
        defines=['HAVE_CONFIG_H'],
        lib=['ecell4-core', 'gsl', 'gslcblas', 'm', 'gfrd'],
        libpath = ['../../../epdp'],
        use='ecell4-egfrd')
