#! /usr/bin/env python
# encoding: utf-8

from waflib.Tools import waf_unit_test
from waflib import Logs

top = '.'
out = 'build'

pyfiles = [
    'ecell4/util/__init__.py',
    'ecell4/util/particle_space.py',
    'ecell4/util/spatiocyte_tools.py',
    'ecell4/util/bdml.py',
    'ecell4/util/particle_spatiocyte_loader.py',
    'ecell4/util/lattice_space.py',
    'ecell4/util/sbml_exporter.py'
    ]


def options(opt):
    opt.load('compiler_cxx') # XXX: DUMMY
    opt.load('python')

def configure(conf):
    conf.load('compiler_cxx') # XXX: DUMMY
    conf.load('python')
    conf.check_python_headers()

def build(bld):
    bld.install_files('${PYTHONDIR}/ecell4/util', pyfiles)
