#! /usr/bin/env python
# encoding: utf-8


def configure(conf):
    pass

def build(bld):
    bld.program(
        source = 'main.cpp',
        target = 'hardbody',
        includes = ['../..'],
        defines = ['HAVE_CONFIG_H', 'HAVE_INLINE'],
        lib = ['ecell4-core', 'gsl', 'gslcblas', 'm', 'ecs', 'emc',
               # 'ecell3-spatiocyte-stepper'],
               ':/home/kaizu/src/ecell3-spatiocyte/SpatiocyteStepper.so'],
        use = 'ecell4-spatiocyte')
