#! /usr/bin/env python
# encoding: utf-8


def configure(conf):
    pass

def build(bld):
    bld.program(
        source = 'main.cpp',
        target = '2010.arjunan.syst.synth.biol',
        includes = ['../..'],
        defines = ['HAVE_CONFIG_H', 'HAVE_INLINE'],
        lib = ['ecell4-core', 'gsl', 'gslcblas', 'm', 'ecs', 'emc',
               'hdf5', 'hdf5_cpp'],
        use = 'ecell4-spatiocyte')
