#! /usr/bin/env python
# encoding: utf-8
#
top = '.'
out = 'build'

from waflib.Tools import waf_unit_test
from waflib import Logs

pxdfiles = [
    'ecell4/ode.pxd'
    ]

def options(opt):
    opt.load('compiler_cxx')
    opt.load('compiler_c')
    opt.load('python')
    opt.load('cython')
    # opt.load('cython_cache', tooldir='.')

def configure(conf):
    conf.load('compiler_cxx')
    conf.load('compiler_c')
    conf.load('python')
    conf.check_python_headers()

    conf.find_program('cython')
    try:
        conf.load('cython')
    except conf.errors.ConfigurationError:
        Logs.warn('cython not found')

def build(bld):
    bld.install_files('${PYTHONDIR}/ecell4', pxdfiles)
    bld.env.CYTHONFLAGS += ('-I${PYTHONDIR}', )
    bld(
        features = 'cxx cxxshlib pyext',
        source = 'ecell4/ode.pyx',
        target = 'ode',
        # includes = ['.'],
        install_path = '${PYTHONDIR}/ecell4',
        lib = ['ecell4-core', 'ecell4-ode'])
