#! /usr/bin/env python
# encoding: utf-8

def configure(conf):
    pass

def build(bld):
    bld.program(
        features='cxx cxxprogram test',
        source='ODESimulator_test.cpp',
        target='ODESimulator_test',
        includes=['..'],
        lib=['ecell4-core', 'gsl', 'gslcblas', 'm'],
        use='ecell4-ode')
