#! /usr/bin/env python
# encoding: utf-8


def configure(conf):
    pass

def build(bld):
    bld.program(
        source = 'main.cpp',
        target = 'mapk',
        includes = ['../..'],
        defines = ['HAVE_CONFIG_H', 'HAVE_INLINE'],
        lib = ['gsl', 'gslcblas', 'm', 'ecell4-core', 'gfrd'],
        use = 'ecell4-egfrd')
