#! /usr/bin/env python
# encoding: utf-8

def configure(conf):
    pass

def build(bld):
    bld.program(
        features = 'cxx cxxprogram test',
        source = ['SpatiocyteSimulator_test.cpp'],
        target = 'SpatiocyteSimulator_test',
        includes = ['..'],
        defines = ['HAVE_CONFIG_H', 'HAVE_INLINE'],
        lib = ['ecell4-core', 'gsl', 'gslcblas', 'm'],
        use = 'ecell4-spatiocyte')
