#! /usr/bin/env python
# encoding: utf-8

def configure(conf):
    pass

def build(bld):
    bld.program(
        features='cxx cxxprogram test',
        source='Position3_test.cpp',
        includes='..',
        target='Position3_test',
        lib=['gsl', 'gslcblas', 'm'],
        use='ecell4-core',
    )

    bld.program(
        features='cxx cxxprogram test',
        source='CompartmentSpace_test.cpp',
        includes='..',
        target='CompartmentSpace_test',
        lib=['gsl', 'gslcblas', 'm'],
        use='ecell4-core',
    )

    bld.program(
        features='cxx cxxprogram test',
        source='Species_test.cpp',
        includes='..',
        target='Species_test',
        lib=['gsl', 'gslcblas', 'm'],
        use='ecell4-core',
    )
