#! /usr/bin/env python
# encoding: utf-8

def configure(conf):
    pass

def build(bld):
    bld.program(
        features='cxx cxxprogram test',
        source='BDWorld_test.cpp',
        target='BDWorld_test',
        includes=['..'],
        lib=['ecell4-core', 'gsl', 'gslcblas', 'm'],
        use='unittestmain CPPUNIT')

    bld.program(
        features='cxx cxxstlib',
        source='main.cpp',
        use='CPPUNIT',
        target='unittestmain')
