#! /usr/bin/env python
# encoding: utf-8

def configure(conf):
    pass

def build(bld):
    bld.program(
        features='cxx cxxprogram test',
        source='BDWorld_test.cpp',
        target='BDWorld_test',
        includes=['..'],
        lib=['ecell4-core', 'gsl', 'gslcblas', 'm'],
        use='ecell4-bd')

    bld.program(
        features='cxx cxxprogram test',
        source='BDSimulator_test.cpp',
        target='BDSimulator_test',
        includes=['..'],
        lib=['ecell4-core', 'gsl', 'gslcblas', 'm'],
        use='ecell4-bd')
