package:
  name: ecell4_base
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'dev') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  script_env:
    - CC
    - CXX

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
    - pybind11
    - cmake
    - hdf5
    - gsl

  run:
    - python
    - vs2015_runtime  # [win]

about:
  summary: E-Cell4 project built with pybind11.
  license_file: LICENSE
